# fly.toml file generated for smart-factory-energy-optimizer

app = "smart-factory-energy-optimizer"
primary_region = "sea"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  CORS_ORIGINS = "*"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  strategy = "immediate"