services:
  - type: web
    name: smart-factory-api
    runtime: python3
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: HOST
        value: "0.0.0.0"
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "*"
    # Auto-deploy when you push to main branch
    autoDeploy: true