name: smart-factory-backend
services:
  - type: web
    name: smart-factory-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
    # Auto-deploy when you push to main branch
    autoDeploy: true